# Generated by Django 4.2.1 on 2025-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc_gen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSCEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspective', models.CharField(choices=[('Financial', 'Financial'), ('Customer', 'Customer'), ('Internal', 'Internal'), ('Learning & Growth', 'Learning & Growth')], max_length=32)),
                ('objective', models.CharField(max_length=255)),
                ('measure', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('actual', models.CharField(max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
