# Generated by Django 4.2.1 on 2025-07-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc_gen', '0002_bscentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bscentry',
            name='batch_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bscentry',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
