# Generated by Django 5.2.3 on 2025-07-16 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc_gen', '0005_customerbsc_batch_name_financialbsc_batch_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', max_length=20)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc_gen.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('batch_id', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc_gen.organization')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc_gen.organization')),
            ],
        ),
        migrations.DeleteModel(
            name='BSCEntry',
        ),
        migrations.AddField(
            model_name='customerbsc',
            name='alert_threshold',
            field=models.DecimalField(decimal_places=2, default=0.8, help_text='Alert when performance drops below this ratio', max_digits=5),
        ),
        migrations.AddField(
            model_name='customerbsc',
            name='benchmark_value',
            field=models.CharField(blank=True, help_text='Industry benchmark value', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerbsc',
            name='is_smart_goal',
            field=models.BooleanField(default=False, help_text='Indicates if this is a SMART goal'),
        ),
        migrations.AddField(
            model_name='customerbsc',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerbsc',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Importance weight (0.1 to 5.0)', max_digits=5),
        ),
        migrations.AddField(
            model_name='financialbsc',
            name='alert_threshold',
            field=models.DecimalField(decimal_places=2, default=0.8, help_text='Alert when performance drops below this ratio', max_digits=5),
        ),
        migrations.AddField(
            model_name='financialbsc',
            name='benchmark_value',
            field=models.CharField(blank=True, help_text='Industry benchmark value', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialbsc',
            name='is_smart_goal',
            field=models.BooleanField(default=False, help_text='Indicates if this is a SMART goal'),
        ),
        migrations.AddField(
            model_name='financialbsc',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialbsc',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Importance weight (0.1 to 5.0)', max_digits=5),
        ),
        migrations.AddField(
            model_name='internalbsc',
            name='alert_threshold',
            field=models.DecimalField(decimal_places=2, default=0.8, help_text='Alert when performance drops below this ratio', max_digits=5),
        ),
        migrations.AddField(
            model_name='internalbsc',
            name='benchmark_value',
            field=models.CharField(blank=True, help_text='Industry benchmark value', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internalbsc',
            name='is_smart_goal',
            field=models.BooleanField(default=False, help_text='Indicates if this is a SMART goal'),
        ),
        migrations.AddField(
            model_name='internalbsc',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalbsc',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Importance weight (0.1 to 5.0)', max_digits=5),
        ),
        migrations.AddField(
            model_name='learninggrowthbsc',
            name='alert_threshold',
            field=models.DecimalField(decimal_places=2, default=0.8, help_text='Alert when performance drops below this ratio', max_digits=5),
        ),
        migrations.AddField(
            model_name='learninggrowthbsc',
            name='benchmark_value',
            field=models.CharField(blank=True, help_text='Industry benchmark value', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learninggrowthbsc',
            name='is_smart_goal',
            field=models.BooleanField(default=False, help_text='Indicates if this is a SMART goal'),
        ),
        migrations.AddField(
            model_name='learninggrowthbsc',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learninggrowthbsc',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Importance weight (0.1 to 5.0)', max_digits=5),
        ),
        migrations.AddField(
            model_name='customerbsc',
            name='action_plans',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_objectives', to='bsc_gen.actionplan'),
        ),
        migrations.AddField(
            model_name='financialbsc',
            name='action_plans',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_objectives', to='bsc_gen.actionplan'),
        ),
        migrations.AddField(
            model_name='internalbsc',
            name='action_plans',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_objectives', to='bsc_gen.actionplan'),
        ),
        migrations.AddField(
            model_name='learninggrowthbsc',
            name='action_plans',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_objectives', to='bsc_gen.actionplan'),
        ),
        migrations.AddField(
            model_name='customerbsc',
            name='strategy_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bsc_gen.strategymap'),
        ),
        migrations.AddField(
            model_name='financialbsc',
            name='strategy_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bsc_gen.strategymap'),
        ),
        migrations.AddField(
            model_name='internalbsc',
            name='strategy_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bsc_gen.strategymap'),
        ),
        migrations.AddField(
            model_name='learninggrowthbsc',
            name='strategy_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bsc_gen.strategymap'),
        ),
    ]
